# version: '3.4'
# services:
#   kafka:
#     image: "bitnami/kafka"
#     hostname: "kafka"
#     ports:
#       - "15672:15672"
#       - "5672:5672"
#     labels:
#       NAME: "kafka"
#     volumes:
#     - /path/to/kafka-persistence:/bitnami/kafka

# version: '2'

# networks:
#   app-tier:
#     driver: bridge

# services:
#   zookeeper:
#     image: 'bitnami/zookeeper:latest'
#     networks:
#       - app-tier
#   kafka:
#     image: 'bitnami/kafka:latest'
#     networks:
#       - app-tier
#   myapp:
#     image: 'YOUR_APPLICATION_IMAGE'
#     networks:
#       - app-tier

version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
